version: "3.5"
services:
  dev:
    image: "docker.io/gabyxgabyx/technical-markdown:latest"
    security_opt:
      - seccomp:unconfined
    cap_add:
      - SYS_PTRACE
    environment:
      - DISPLAY=host.docker.internal:0.0
    volumes:
      - ..:/workspace
      - ./shell:/home/developer/.shell
      - ./python.requirements:/container-setup/python.add-requirements
      - ~/.gitconfig:/container-setup/.gitconfig-host:ro
      - /etc/localtime:/etc/localtime
      - /etc/timezone:/etc/timezone
    command: tail -f /dev/null
